<%@ page import="org.transitclock.reports.ReportsConfig" %>
<div <% if (!ReportsConfig.isShowPredictionSource()) out.print("class=\"hidden\""); %>>
  <label for="source" class="block text-sm font-medium text-gray-900 mb-1"><fmt:message key="div.psource"/></label>
  <select id="source" name="source"
    title="Specifies which prediction system to display data for. Selecting 'TransitClock' means will only show prediction data generated by TheTransitClock. If there is another prediction source then can select 'Other'. And selecting 'All' displays data for all prediction sources."
    class="block w-full max-w-md rounded-md border-0 py-1.5 pl-3 pr-10 text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 focus:ring-2 focus:ring-inset focus:ring-indigo-600 sm:text-sm sm:leading-6">
    <option value="TransitClock">TransitClock</option>
    <option value="Other"><fmt:message key="div.other"/></option>
    <option value=""><fmt:message key="div.pall"/></option>
  </select>
</div>
