<%@ page import="org.transitclock.reports.ReportsConfig" %>
<div <% if (!ReportsConfig.isShowPredictionSource()) out.print("class=\"hidden\""); %>>
  <label for="source" class="block text-sm font-medium text-neutral-700 mb-1"><fmt:message key="div.psource"/></label>
  <select id="source" name="source"
    title="Specifies which prediction system to display data for. Selecting 'TransitClock' means will only show prediction data generated by TheTransitClock. If there is another prediction source then can select 'Other'. And selecting 'All' displays data for all prediction sources."
    class="form-control w-full max-w-md">
    <option value="TransitClock">TransitClock</option>
    <option value="Other"><fmt:message key="div.other"/></option>
    <option value=""><fmt:message key="div.pall"/></option>
  </select>
</div>
