package org.transitclock.pipelinetests;

import static org.assertj.core.api.Assertions.assertThat;

import java.util.List;
import java.util.concurrent.atomic.AtomicLong;

import org.hibernate.Session;
import org.hibernate.criterion.Restrictions;
import org.junit.ClassRule;
import org.junit.Test;
import org.transitclock.configData.AgencyConfig;
import org.transitclock.core.AvlProcessor;
import org.transitclock.db.hibernate.HibernateUtils;
import org.transitclock.db.structs.ArrivalDeparture;
import org.transitclock.db.structs.AvlReport;
import org.transitclock.db.structs.AvlReport.AssignmentType;

/**
 * Behavior tests that verify records generated by the pipeline actually
 * make it into the database via {@link org.transitclock.db.hibernate.DataDbLogger}.
 *
 * <p>{@link ArrivalDepartureBehaviorTest} covers the ehcache path: records
 * show up in {@code StopArrivalDepartureCache} after an advancement. Those
 * checks would stay green if DataDbLogger (the async batched writer that
 * feeds the actual DB tables) silently dropped records — a regression that
 * would cost production its historical data but leave the in-memory caches
 * looking healthy. These tests close that gap by querying the DB directly
 * with Hibernate after driving the pipeline.
 *
 * <p>DataDbLogger is asynchronous: a background thread drains its queues
 * and commits batches. Tests therefore poll the DB for records rather than
 * asserting-and-immediately-failing — see {@link #waitForDbRows}.
 */
public class DbPersistenceBehaviorTest {

	@ClassRule
	public static final CoreHarness CORE = CoreHarness.withWmata5A();

	private static final String BLOCK_ID = "SE-08";
	private static final String TRIP_ID = "868588900";

	private static final String STOP_FIRST_ID = "14253";
	private static final double STOP_FIRST_LAT = 38.953562;
	private static final double STOP_FIRST_LON = -77.447485;

	private static final String STOP_NEXT_ID = "13056";
	private static final double STOP_NEXT_LAT = 38.951704;
	private static final double STOP_NEXT_LON = -77.383009;

	/** 2016-06-20 11:50:00 America/New_York → 15:50:00 UTC. Pins the AVL
	 *  timestamps used by these tests. */
	private static final long AVL_AT_FIRST_STOP_EPOCH_MS = 1466437800000L;

	/** Keeps AVL timestamps strictly distinct across tests in this class. */
	private static final AtomicLong nextTime = new AtomicLong(AVL_AT_FIRST_STOP_EPOCH_MS);

	/** Upper bound on how long to wait for the DataDbLogger background
	 *  thread to flush pipeline output to the DB. In practice the queue
	 *  drains in under a second; 10 s is a wide safety margin. */
	private static final long DB_FLUSH_TIMEOUT_MS = 10_000L;

	/** Poll interval while waiting for DB writes. Small enough that a
	 *  quick-draining queue is detected promptly, large enough to avoid
	 *  hammering HSQL with criteria queries. */
	private static final long DB_POLL_INTERVAL_MS = 100L;

	private static AvlReport avlReport(String vehicleId, double lat, double lon, long timeMs) {
		return new AvlReport(vehicleId, timeMs, lat, lon,
				Float.NaN, Float.NaN, "test");
	}

	/**
	 * Pushes two AVL reports for {@code vehicleId} — first at stop 14253,
	 * then at stop 13056 eight minutes later — matching the shape of
	 * {@link ArrivalDepartureBehaviorTest}'s helper. This sequence causes
	 * ArrivalDepartureGenerator to emit records which DataDbLogger then
	 * persists.
	 */
	private static void advanceVehicleFromFirstStopToNext(String vehicleId) {
		long t1 = nextTime.getAndAdd(1);
		CORE.setNow(t1);
		AvlReport first = avlReport(vehicleId, STOP_FIRST_LAT, STOP_FIRST_LON, t1);
		first.setAssignment(BLOCK_ID, AssignmentType.BLOCK_ID);
		AvlProcessor.getInstance().processAvlReport(first);

		long t2 = t1 + 8L * 60_000L;
		nextTime.updateAndGet(cur -> Math.max(cur, t2 + 1));
		CORE.setNow(t2);
		AvlReport second = avlReport(vehicleId, STOP_NEXT_LAT, STOP_NEXT_LON, t2);
		second.setAssignment(BLOCK_ID, AssignmentType.BLOCK_ID);
		AvlProcessor.getInstance().processAvlReport(second);
	}

	@SuppressWarnings("unchecked")
	private static List<ArrivalDeparture> queryArrivalDeparturesForVehicle(String vehicleId) {
		try (Session session = HibernateUtils.getSession(AgencyConfig.getAgencyId())) {
			return session.createCriteria(ArrivalDeparture.class)
					.add(Restrictions.eq("vehicleId", vehicleId))
					.list();
		}
	}

	@SuppressWarnings("unchecked")
	private static List<AvlReport> queryAvlReportsForVehicle(String vehicleId) {
		try (Session session = HibernateUtils.getSession(AgencyConfig.getAgencyId())) {
			return session.createCriteria(AvlReport.class)
					.add(Restrictions.eq("vehicleId", vehicleId))
					.list();
		}
	}

	/**
	 * Polls the DB via {@code fetcher} until at least {@code minRows} rows
	 * are returned or the timeout elapses. Returns the final list (may
	 * still be short if the timeout fired — callers should assert on what
	 * they care about).
	 */
	private static <T> List<T> waitForDbRows(java.util.function.Supplier<List<T>> fetcher,
			int minRows) {
		long deadline = System.currentTimeMillis() + DB_FLUSH_TIMEOUT_MS;
		List<T> rows = fetcher.get();
		while (rows.size() < minRows && System.currentTimeMillis() < deadline) {
			try {
				Thread.sleep(DB_POLL_INTERVAL_MS);
			} catch (InterruptedException ie) {
				Thread.currentThread().interrupt();
				break;
			}
			rows = fetcher.get();
		}
		return rows;
	}

	// ---------- Tests ----------

	@Test
	public void avlReportsAreWrittenToDbAfterProcessing() {
		// The simplest persistence check: every AVL processed through
		// AvlProcessor should land in the AvlReports table. DataDbLogger's
		// AvlReport queue is the most heavily exercised path in production,
		// and a regression that silently drops AVLs here would leave the
		// system unable to replay history.
		advanceVehicleFromFirstStopToNext("v-db-avl");

		List<AvlReport> rows = waitForDbRows(
				() -> queryAvlReportsForVehicle("v-db-avl"), 2);
		assertThat(rows)
				.as("both AVL reports for the vehicle should be persisted within the timeout")
				.hasSizeGreaterThanOrEqualTo(2);
	}

	@Test
	public void arrivalDepartureRecordsAreWrittenToDbAfterAdvancement() {
		// Advancing from stop 14253 to stop 13056 produces at least a
		// Departure at 14253 and an Arrival at 13056. Both should appear
		// in the ArrivalsDepartures table. This is the gap
		// ArrivalDepartureBehaviorTest leaves uncovered: that the cache
		// path is only one of two destinations, and the DB path is the
		// one that feeds every downstream analytics user.
		advanceVehicleFromFirstStopToNext("v-db-ad");

		List<ArrivalDeparture> rows = waitForDbRows(
				() -> queryArrivalDeparturesForVehicle("v-db-ad"), 1);
		assertThat(rows)
				.as("at least one ArrivalDeparture row for the vehicle should be persisted")
				.isNotEmpty();
	}

	@Test
	public void persistedArrivalDepartureRecordsCarryExpectedMetadata() {
		// Shape check on the first persisted row: the block, trip, and
		// vehicle id should all match what we pushed. Catches regressions
		// where fields get dropped or swapped during Hibernate marshalling
		// — a class of bug that would be invisible at the in-memory
		// cache layer but would corrupt every historical record.
		advanceVehicleFromFirstStopToNext("v-db-meta");

		List<ArrivalDeparture> rows = waitForDbRows(
				() -> queryArrivalDeparturesForVehicle("v-db-meta"), 1);
		assertThat(rows).isNotEmpty();

		ArrivalDeparture first = rows.get(0);
		assertThat(first.getVehicleId()).isEqualTo("v-db-meta");
		assertThat(first.getBlockId()).isEqualTo(BLOCK_ID);
		assertThat(first.getTripId()).isEqualTo(TRIP_ID);
		assertThat(first.getStopId())
				.as("the first row should be at one of the two stops we advanced through")
				.isIn(STOP_FIRST_ID, STOP_NEXT_ID);
	}

	@Test
	public void bothArrivalAndDepartureVariantsArePersistedForTheAdvancement() {
		// Counterpart to persistedArrivalDepartureRecordsCarryExpectedMetadata:
		// that test just pulled the first row. Here we wait for both an
		// arrival and a departure to show up. A regression that persisted
		// only the arrival half (or only the departure half) would leave
		// historical data unable to compute dwell times — a subtle
		// downstream failure worth catching at this layer.
		advanceVehicleFromFirstStopToNext("v-db-variants");

		List<ArrivalDeparture> rows = waitForDbRows(
				() -> queryArrivalDeparturesForVehicle("v-db-variants"), 2);
		assertThat(rows)
				.as("at least two records (for the advancement) should persist")
				.hasSizeGreaterThanOrEqualTo(2);

		boolean hasArrival = rows.stream().anyMatch(ArrivalDeparture::isArrival);
		boolean hasDeparture = rows.stream().anyMatch(ad -> !ad.isArrival());
		assertThat(hasArrival)
				.as("at least one persisted record should be an arrival")
				.isTrue();
		assertThat(hasDeparture)
				.as("at least one persisted record should be a departure")
				.isTrue();
	}
}
